version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app
    depends_on:
      - mongo
